services:
    proxy:
        image: steveltn/https-portal:1.25.2
        ports:
            - 80:80
            - 443:443
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./.ssl:/var/lib/https-portal
        env_file:
            - .env
        environment:
            STAGE: ${SITE_STAGE:-${STAGE:-local}}
            ERROR_LOG: stdout
            ACCESS_LOG: stderr
            ACCESS_LOG_INCLUDE_HOST: on
            RESOLVER: 127.0.0.11
            CUSTOM_NGINX_SERVER_CONFIG_BLOCK: |
                location ~ ^ {
                    proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
                    proxy_set_header Host $$host;
                    proxy_ssl_verify off;
                    proxy_ssl_server_name on;
                    proxy_pass http://$${host}.yxorp$${request_uri};
                    proxy_http_version 1.1;
                }
        networks:
            public:

networks:
    public:
        name: yxorp
